-- création MCD Majhong


/*
DROP TABLE COLLECTION;
DROP TABLE JOUEUR;
DROP TABLE CONNEXION;
DROP TABLE NIVEAU;
DROP TABLE PARTIE;
DROP TABLE COORDONNES;
DROP TABLE CARTE;
DROP TABLE CASES;
DROP TABLE SELECTIONNER;
*/

CREATE TABLE COLLECTION(
id_collection INT CONSTRAINT pk_collection PRIMARY KEY NOT NULL,
nom_collection VARCHAR(20) NOT NULL
);
CREATE TABLE JOUEUR(
id_joueur INT CONSTRAINT pk_joueur PRIMARY KEY NOT NULL,
nom VARCHAR(50) NOT NULL,
prenom VARCHAR(20) NOT NULL,
nom_utilisateur VARCHAR(20) NOT NULL,
pseudo VARCHAR(50) NOT NULL,
mot_de_passe VARCHAR(300) NOT NULL,
administateur NUMBER(1) NOT NULL
);
CREATE TABLE CONNEXION(
id_connexion INT CONSTRAINT pk_connexion PRIMARY KEY NOT NULL,
date_connexion TIMESTAMP NOT NULL,
id_joueur INT CONSTRAINT fk_joueur references JOUEUR(id_joueur) NOT NULL
);

CREATE TABLE NIVEAU(
id_niveau INT CONSTRAINT pk_niveau PRIMARY KEY NOT NULL,
nom_niveau VARCHAR(20) NOT NULL
);


CREATE TABLE PARTIE(
id_partie INT CONSTRAINT pk_game PRIMARY KEY NOT NULL,
dateDeb_partie TIMESTAMP NOT NULL,
dateFIN_game TIMESTAMP NOT NULL,
resultat NUMBER(1) NOT NULL,
score INT,
id_joueur INT CONSTRAINT fk_joueur2 references JOUEUR(id_joueur) NOT NULL,
id_niveau INT CONSTRAINT fk_niveau2 REFERENCES NIVEAU(id_niveau) NOT NULL
);


CREATE TABLE COORDONNES(
id_coordonnees INT CONSTRAINT pk_coordonnees PRIMARY KEY NOT NULL,
x INT NOT NULL,
y INT NOT NULL,
z INT NOT NULL,
statut NUMBER(1) NOT NULL,
vide NUMBER(1) NOT NULL,
id_niveau INT CONSTRAINT fk_niveau3 REFERENCES NIVEAU(id_niveau) NOT NULL
);


CREATE TABLE CARTE(
id_carte INT CONSTRAINT pk_carte PRIMARY KEY NOT NULL,
chemin_carte VARCHAR(50) NOT NULL,
id_collection INT CONSTRAINT fk_collection4 REFERENCES COLLECTION(id_collection) NOT NULL
);


CREATE TABLE CASES(
id_cases INT CONSTRAINT pk_cases PRIMARY KEY NOT NULL,
id_coordonnes INT CONSTRAINT fk_coordonnees REFERENCES COORDONNES(id_coordonnees) NOT NULL,
id_carte INT CONSTRAINT fk_carte REFERENCES CARTE(id_carte) NOT NULL,
id_partie INT CONSTRAINT fk_partie REFERENCES PARTIE(id_partie) NOT NULL
);


CREATE TABLE SELECTIONNER(
id_selectionner INT CONSTRAINT pk_selectionner PRIMARY KEY NOT NULL,
date_selection TIMESTAMP NOT NULL,
type_selection NUMBER(1) NOT NULL,
id_carte INT CONSTRAINT fk_carte5 REFERENCES CARTE(id_carte) NOT NULL,
id_partie INT CONSTRAINT fk_partie5 REFERENCES PARTIE(id_partie) NOT NULL
);