/* Insertion Majhong */

INSERT INTO COLLECTION VALUES (1, 'FORMES GEOMETRIQUES');
INSERT INTO COLLECTION VALUES (2, 'FLEURS');
INSERT INTO COLLECTION VALUES (3, 'ASTERIX');
INSERT INTO COLLECTION VALUES (4, 'VOITURES');
INSERT INTO COLLECTION VALUES (5, 'SATR WARS');
INSERT INTO COLLECTION VALUES (6, 'COULEURS');
INSERT INTO COLLECTION VALUES (7, 'LUNETTES');
INSERT INTO COLLECTION VALUES (8, 'FRUITS');
INSERT INTO COLLECTION VALUES (9, 'SCHTROUMF');
INSERT INTO COLLECTION VALUES (10, 'CARACTERE CHINOIS');

INSERT INTO NIVEAU VALUES (1, 'LES FORMES', 1);
INSERT INTO NIVEAU VALUES (2, 'LES FLEURS', 2);
INSERT INTO NIVEAU VALUES (3, 'ASTERIX', 3);
INSERT INTO NIVEAU VALUES (4, 'LES VOITURES', 4);
INSERT INTO NIVEAU VALUES (5, 'STAR WARS', 5);
INSERT INTO NIVEAU VALUES (6, 'LES COULEURS', 6);
INSERT INTO NIVEAU VALUES (7, 'LES LUNETTES', 7);
INSERT INTO NIVEAU VALUES (8, 'LES FRUITS', 8);
INSERT INTO NIVEAU VALUES (9, 'LES SCHTROUMFS', 9);
INSERT INTO NIVEAU VALUES (10, 'CARACTERES CHINOIS', 10);


